# Generated by Django 5.0 on 2025-12-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_materia', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('profesor', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=50)),
                ('tareas', models.JSONField(blank=True, default=dict)),
                ('calificaciones', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
