# Generated by Django 5.0 on 2025-12-11 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
        ('whitelabel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='whitelabel.institution'),
        ),
    ]
