# Generated by Django 5.0 on 2025-12-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tarea', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_entrega', models.DateField()),
                ('materia', models.CharField(max_length=20)),
                ('institucion', models.CharField(max_length=50)),
            ],
        ),
    ]
