# Generated by Django 5.0 on 2025-12-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_key', models.CharField(help_text='Clave con la que se sincroniza en Firebase (ejemplo: institucion_1)', max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('color_primario', models.CharField(default='#1A73E8', max_length=10)),
                ('color_secundario', models.CharField(default='#185ABC', max_length=10)),
                ('color_fondo', models.CharField(default='#F5F5F5', max_length=10)),
                ('color_texto', models.CharField(default='#000000', max_length=10)),
                ('texto_bienvenida', models.CharField(blank=True, max_length=300, null=True)),
                ('texto_descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('mostrar_anuncios', models.BooleanField(default=True)),
                ('mostrar_calificaciones', models.BooleanField(default=True)),
                ('mostrar_tareas', models.BooleanField(default=True)),
            ],
        ),
    ]
