# Generated by Django 5.0 on 2025-12-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('teacher', 'Profesor'), ('student', 'Estudiante')], default='student', max_length=10),
        ),
    ]
