# Generated by Django 5.0 on 2025-12-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante_id', models.CharField(max_length=20)),
                ('materia_id', models.CharField(max_length=20)),
                ('calificacion', models.PositiveIntegerField()),
                ('institucion', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('estudiante_id', 'materia_id')},
            },
        ),
    ]
